/**
 * Shashtna Console — native shell contract (pure, unit-tested).
 *
 * The native shells (Phase 10: Capacitor Android, Tauri Windows) are thin
 * wrappers around the same web Console. The only things they talk to the
 * server about directly live under /api/console/v1:
 *
 *   - a device credential, bound to one staff sign-in, kept by the shell in
 *     OS secure storage (Android Keystore / Windows Credential Manager);
 *   - exchanging it for the normal HttpOnly session cookie;
 *   - listing, renaming, revoking and signing out devices.
 *
 * Nothing here is a second auth system: the session the exchange creates
 * is the existing signed staff token, checked by the same code on every
 * request (role re-read, 7-day staff maximum, sign-out-everywhere).
 */

export const CONSOLE_API_VERSION = "v1";
export const CONSOLE_API_BASE = `/api/console/${CONSOLE_API_VERSION}`;

/**
 * Production origin the shells load. No custom domain is confirmed yet;
 * App Links / universal links bind to this host, so it must be decided
 * before the deep-link phase.
 */
export const CONSOLE_ORIGIN = "https://shashtna.netlify.app";

/**
 * Custom URL scheme reserved for the Console shells (desktop deep links).
 * Not "shashtna://": the customer app (ODEN-AI/shashtna-mobile) already
 * registers that scheme. Shashtna Player registers none. Runtime handling
 * belongs to the shell phase — this is the reserved name only.
 */
export const CONSOLE_URL_SCHEME = "shashtna-console";

export const CONSOLE_PLATFORMS = ["WINDOWS", "ANDROID", "IOS", "WEB"] as const;
export type ConsolePlatform = (typeof CONSOLE_PLATFORMS)[number];

/** A shell session is short; the shell re-exchanges its credential. */
export const DEVICE_SESSION_TTL_SECONDS = 12 * 60 * 60;
/** Non-revoked devices one staff member may have. */
export const MAX_DEVICES_PER_USER = 20;
/** lastSeenAt is written at most this often per device. */
export const LAST_SEEN_INTERVAL_MS = 15 * 60 * 1000;

const LABEL_MAX = 60;
const VERSION_PATTERN = /^[0-9A-Za-z][0-9A-Za-z.+-]{0,31}$/;

/**
 * Device credential: "scd1.<deviceId>.<secret>". The secret is 32 random
 * bytes (base64url, 43 chars) generated by the server and shown once; the
 * database keeps only its SHA-256 verifier. The device id alone grants
 * nothing.
 */
const CREDENTIAL_PATTERN = /^scd1\.([1-9]\d{0,9})\.([A-Za-z0-9_-]{43})$/;

export function formatDeviceCredential(deviceId: number, secret: string) {
  return `scd1.${deviceId}.${secret}`;
}

export function parseDeviceCredential(value: unknown): { deviceId: number; secret: string } | null {
  if (typeof value !== "string" || value.length > 64) return null;
  const match = CREDENTIAL_PATTERN.exec(value);
  if (!match) return null;
  const deviceId = Number(match[1]);

  return Number.isSafeInteger(deviceId) ? { deviceId, secret: match[2] } : null;
}

/** Collapse whitespace, drop control characters; null when unusable. */
export function cleanDeviceLabel(value: unknown) {
  if (typeof value !== "string") return null;
  const label = value.replace(/[\u0000-\u001f\u007f]/g, "").replace(/\s+/g, " ").trim();

  return label.length >= 1 && label.length <= LABEL_MAX ? label : null;
}

export type DeviceInput = { platform: ConsolePlatform; label: string; appVersion: string | null; deviceId: number | null };

/** Strict validation of a registration body. Unknown fields are ignored; userId is never read. */
export function parseDeviceInput(body: unknown): { ok: true; value: DeviceInput } | { ok: false; field: string } {
  if (!body || typeof body !== "object" || Array.isArray(body)) return { ok: false, field: "body" };
  const input = body as Record<string, unknown>;
  const platform = CONSOLE_PLATFORMS.find((item) => item === input.platform);
  if (!platform) return { ok: false, field: "platform" };
  const label = cleanDeviceLabel(input.label);
  if (!label) return { ok: false, field: "label" };

  let appVersion: string | null = null;
  if (input.appVersion !== undefined && input.appVersion !== null && input.appVersion !== "") {
    if (typeof input.appVersion !== "string" || !VERSION_PATTERN.test(input.appVersion)) return { ok: false, field: "appVersion" };
    appVersion = input.appVersion;
  }

  let deviceId: number | null = null;
  if (input.deviceId !== undefined && input.deviceId !== null) {
    if (typeof input.deviceId !== "number" || !Number.isSafeInteger(input.deviceId) || input.deviceId <= 0) return { ok: false, field: "deviceId" };
    deviceId = input.deviceId;
  }

  return { ok: true, value: { platform, label, appVersion, deviceId } };
}

/**
 * When a device session ends (seconds): never later than the 7-day staff
 * maximum counted from the password sign-in the device was bound to.
 */
export function deviceSessionExpiry(authenticatedAtSec: number, nowSec: number, staffMaxAgeSec: number) {
  return Math.min(nowSec + DEVICE_SESSION_TTL_SECONDS, authenticatedAtSec + staffMaxAgeSec);
}

/** The metadata a device list may show — never hashes, tokens or push tokens. */
export type DeviceView = {
  id: number;
  userId: number;
  platform: string;
  label: string;
  appVersion: string | null;
  createdAt: string;
  lastSeenAt: string | null;
  revokedAt: string | null;
  status: "ACTIVE" | "SIGNED_OUT" | "REVOKED";
};

export function deviceStatus(device: { revokedAt: unknown; credentialHash: unknown }): DeviceView["status"] {
  if (device.revokedAt) return "REVOKED";
  return device.credentialHash ? "ACTIVE" : "SIGNED_OUT";
}

// ------------------------------------------------------------------ v1 contract (Phase 10B)

/**
 * Error envelope of every /api/console/v1 failure:
 *   { ok: false, code, message, field?, retryAfter? }
 * `code` is stable and machine-readable; `message` is Arabic UI text and may
 * change. Clients branch on the kind (derived from code/status), never on
 * the message. No stack traces, secrets or credentials are ever included.
 */
export const CONSOLE_ERROR_CODES = {
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  INVALID: 400,
  INVALID_JSON: 400,
  UNSUPPORTED_MEDIA_TYPE: 415,
  TOO_LARGE: 413,
  NOT_FOUND: 404,
  DEVICE_LIMIT: 409,
  DEVICE_REVOKED: 409,
  RATE_LIMITED: 429,
  SERVER_ERROR: 500,
} as const;

export type ConsoleErrorCode = keyof typeof CONSOLE_ERROR_CODES;

/** What a client needs to decide: re-auth, show "no permission", fix input, back off, retry. */
export type ConsoleErrorKind = "unauthenticated" | "forbidden" | "invalid" | "not_found" | "conflict" | "throttled" | "server" | "network" | "timeout";

export type ConsoleErrorBody = { ok: false; code: ConsoleErrorCode | string; message: string; field?: string; retryAfter?: number };

export function consoleErrorKind(status: number): ConsoleErrorKind {
  if (status === 401) return "unauthenticated";
  if (status === 403) return "forbidden";
  if (status === 404) return "not_found";
  if (status === 409) return "conflict";
  if (status === 429) return "throttled";
  if (status === 400 || status === 413 || status === 415 || status === 422) return "invalid";
  return "server";
}

export type ConsoleUser = { id: number; name: string; role: string };
export type ConsoleDeviceRef = { id: number; platform: string; label: string };

/** POST /session/exchange — the session itself travels as the HttpOnly cookie. */
export type ExchangeResponse = { ok: true; expiresAt: number; user: ConsoleUser; device: ConsoleDeviceRef };
/** POST /session/logout */
export type LogoutResponse = { ok: true; device: boolean };
/** GET /session — who is signed in, with which permissions, until when. */
export type SessionResponse = {
  ok: true;
  user: ConsoleUser;
  permissions: string[];
  session: { kind: "browser" | "device"; deviceId: number | null; issuedAt: number; endsAt: number };
};
/** GET /devices */
export type DevicesResponse = { ok: true; scope: "mine" | "team"; devices: DeviceView[] };
/** POST /devices/register — `credential` is shown once; store it only in OS secure storage. */
export type RegisterResponse = { ok: true; device: DeviceView; credential: string; rebound: boolean };
/** POST /devices/:id/rename and /revoke */
export type DeviceChangeResponse = { ok: true; device: DeviceView; changed: boolean };

/**
 * GET /summary — the native shell's home: attention counts and, only for
 * roles with "finance", the month's money headline. A count key is present
 * only when the role may see that queue; a source that failed to load is
 * listed in `unavailable` (never reported as 0).
 */
export const SUMMARY_COUNT_KEYS = ["orders", "proofs", "activations", "renewals", "resets", "leads", "tickets"] as const;
export type SummaryCountKey = (typeof SUMMARY_COUNT_KEYS)[number];
export type SummaryResponse = {
  ok: true;
  generatedAt: string;
  timeZone: string;
  counts: Partial<Record<SummaryCountKey, number>>;
  finance?: {
    currency: "IQD";
    period: "month";
    revenue: number;
    sales: number;
    previous: number;
    changePct: number | null;
    netProfit: { status: "ok"; amount: number } | { status: "incomplete" };
  };
  unavailable: string[];
};

/** v1 has no paginated lists (devices are capped per user and listed whole). */
export const CONSOLE_PAGINATION = null;
